require 'extensions/emails/models/skeleton/address'
require 'extensions/emails/models/skeleton/mta'

require 'extensions/emails/models/skeleton/campaign'
require 'extensions/emails/models/skeleton/followup'
require 'extensions/emails/models/skeleton/schedule'
require 'extensions/emails/models/skeleton/outreach'

require 'extensions/emails/models/skeleton/uploadleadsjob'
require 'extensions/emails/models/skeleton/uploadleadsmapping'
require 'extensions/emails/models/skeleton/uploadleadsrow'

require 'extensions/emails/models/skeleton/click'
require 'extensions/emails/models/skeleton/open'
require 'extensions/emails/models/skeleton/unsubscribe'
require 'extensions/emails/models/skeleton/delivery'
require 'extensions/emails/models/skeleton/job'
require 'extensions/emails/models/skeleton/link'
require 'extensions/emails/models/skeleton/user'
require 'extensions/emails/models/skeleton/account'
